# Change these first
owner: bronxi47 # Your GitHub organization or username, where this repository lives
repo: uptime_test # The name of this repository

sites:
  - name: Constata WebSite | constata.eu
    url: https://constata.eu
  - name: API Constata Production
    url: https://api.constata.eu
  - name: API Constata Staging
    url: https://api.constata.eu/
  - name: Site broken test
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime_test
  logoUrl: /assets/icon.jpg
  name: Constata UPtime Status
  introTitle: "Esto es una prueba de monitoreo de status de los servicios de Constata"
  introMessage: Para más información visita https://constata.eu
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
